
services:
  frontend:
    image: node:18-alpine
    build: 
      context: ./frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  
