services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    # depends_on:
      # - backend

  # backend:
  #   image: node:18
  #   working_dir: /app
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   command: ["node", "server.js"]